# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/93e48394-46f5-4b4a-9cd7-517738fd2087";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/74AA-EB9C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/a6f2b9d3-1b9b-46b4-ac60-7150c90e48f1" =
    {
      device = "/dev/disk/by-uuid/a6f2b9d3-1b9b-46b4-ac60-7150c90e48f1";
      fsType = "ext4";
      options = [ "x-gvfs-show" ];
    };

  fileSystems."/mnt/f450d8ee-cfcd-4d49-af5e-c18cfab65a09" =
    {
      device = "/dev/disk/by-uuid/f450d8ee-cfcd-4d49-af5e-c18cfab65a09";
      fsType = "btrfs";
      options = [ "x-gvfs-show" ];
    };

  fileSystems."/mnt/dc84c237-143d-4017-94a0-5c8a076d493f" =
    {
      device = "/dev/disk/by-uuid/dc84c237-143d-4017-94a0-5c8a076d493f";
      fsType = "ext4";
      options = [ "x-gvfs-show" ];
    };

  fileSystems."/mnt/880391e3-4e65-4b5e-9670-d58d6a7ef9eb" =
    {
      device = "/dev/disk/by-uuid/880391e3-4e65-4b5e-9670-d58d6a7ef9eb";
      fsType = "ext4";
      options = [ "x-gvfs-show" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/68b7c1d0-491e-4b02-b71f-de781c171f8b"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-1042cdaac853.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-17e3369b254d.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-bc987b1339dd.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tun0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9d4e2ec.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethd92c00c.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
